# Multivariate Linear Regression Model


In [2]:
import pandas as pd
import numpy as np

In [3]:
loan = pd.read_csv("Loan_Data3.csv")
#loan = loan[np.isfinite(loan['Debt_To_Income'])]
print(loan.count())
loan.head()
#loan.to_csv("Loan_Data3.csv",index=False)

Int_Rate             464745
Investment           464745
Term                 464745
Grade                464745
Employment_Len       464745
Home_Ownership       464745
Annual_Income        464745
Purpose              464745
State                464745
Debt_To_Income       464745
Delinquance_2year    464745
dtype: int64


Int_Rate  Investment  Term Grade Employment_Len Home_Ownership  \
0      5.32      4800.0    36     A        2 years       MORTGAGE   
1     16.02     16000.0    60     C        9 years       MORTGAGE   
2     11.99     32600.0    36     B       < 1 year           RENT   
3      6.08     10000.0    36     A        7 years       MORTGAGE   
4      5.32      9000.0    36     A      10+ years            OWN   

   Annual_Income             Purpose State  Debt_To_Income  Delinquance_2year  
0       143000.0             medical    KY            7.88                  0  
1        40000.0  debt_consolidation    TN           32.01                  0  
2        55000.0               house    CA           25.41                  0  
3        54000.0                 car    NY            0.56                  0  
4       158000.0         credit_card    NY            6.74                  0

In [4]:
#One-Hot-Encode the Categorical X Fields


from sklearn.preprocessing import LabelEncoder, StandardScaler


for column in loan.columns:
    
    if loan[column].dtype == type(object):
        le = LabelEncoder()
        loan[column]=le.fit_transform(loan[column].astype(str))
        
    print(loan[column].dtype)
        
        
    
loan.head()

float64
float64
int64
int64
int64
int64
float64
int64
int64
float64
int64


Int_Rate  Investment  Term  Grade  Employment_Len  Home_Ownership  \
0      5.32      4800.0    36      0               2               1   
1     16.02     16000.0    60      2               9               1   
2     11.99     32600.0    36      1              10               4   
3      6.08     10000.0    36      0               7               1   
4      5.32      9000.0    36      0               1               3   

   Annual_Income  Purpose  State  Debt_To_Income  Delinquance_2year  
0       143000.0        7     16            7.88                  0  
1        40000.0        2     41           32.01                  0  
2        55000.0        5      4           25.41                  0  
3        54000.0        0     33            0.56                  0  
4       158000.0        1     33            6.74                  0

In [5]:
## GET RID OF THE ROWS WITH NANs IN THIS COLUMN
#loan = loan[np.isfinite(loan['Debt_To_Income'])]

loan.count()


Int_Rate             464745
Investment           464745
Term                 464745
Grade                464745
Employment_Len       464745
Home_Ownership       464745
Annual_Income        464745
Purpose              464745
State                464745
Debt_To_Income       464745
Delinquance_2year    464745
dtype: int64

In [6]:
#test X and y, report lengths
#x are entire dataset fields short of the one we are predicting(Interest rate), dropped 
X=loan.drop("Int_Rate",axis=1)
y=loan["Int_Rate"].values.reshape(-1, 1)
print(X.shape,y.shape)

(464745, 10) (464745, 1)


In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=.8, test_size=.2, random_state=42)


In [8]:
from sklearn.preprocessing import StandardScaler

X_scaler = StandardScaler().fit(X_train)
y_scaler = StandardScaler().fit(y_train)

In [9]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
y_train_scaled = y_scaler.transform(y_train)
y_test_scaled = y_scaler.transform(y_test)

In [10]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_scaled, y_train_scaled)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
predictions = model.predict(X_test_scaled)
predictions

array([[ 1.13918048],
       [ 0.31726102],
       [ 0.32295932],
       ..., 
       [-0.48029997],
       [-0.48622224],
       [-0.48193921]])

In [18]:
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(y_test_scaled, predictions)
r2 = model.score(X_test_scaled, y_test_scaled)

print(f"MSE: {MSE}, R2: {r2}")

MSE: 0.0583311473153584, R2: 0.9415183873486324


In [25]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
Int_Rate=5.32
Investment = 4000.0
Term = 36
Grade = "C"
Employment_Len = "2 years"
Home_Ownership = "RENT"
Annual_Income=28000.0
Purpose = "major_purchase"
State = "IL"
Debt_To_Income = 12.3
Delinquence_2year = 0

loan_array = [Int_Rate,Investment,Term,Grade,Employment_Len,Home_Ownership,Annual_Income,Purpose,State,Debt_To_Income,Delinquence_2year]

user_input = pd.DataFrame(data=[loan_array],columns=['Int_Rate','Investment', 'Term', 'Grade', 'Employment_Len','Home_Ownership', 'Annual_Income', 'Purpose', 'State', 'Debt_To_Income','Delinquance_2year'])


In [26]:
#construct loan_input
test_loan = pd.read_csv("Loan_Data3.csv")


test_loan=test_loan.append(user_input)

test_loan.tail(1)

Int_Rate  Investment  Term Grade Employment_Len Home_Ownership  \
0      5.32      4000.0    36     C        2 years           RENT   

   Annual_Income         Purpose State  Debt_To_Income  Delinquance_2year  
0        28000.0  major_purchase    IL            12.3                  0

In [27]:
#One Hot Encoding for String X Columns
for column in loan.columns:
   
   if test_loan[column].dtype == type(object):
       le = LabelEncoder()
       test_loan[column]=le.fit_transform(test_loan[column].astype(str))
   print(test_loan[column].dtype)

float64
float64
int64
int64
int64
int64
float64
int64
int64
float64
int64


In [28]:
encoded_input = test_loan.tail(1)
encoded_input

Int_Rate  Investment  Term  Grade  Employment_Len  Home_Ownership  \
0      5.32      4000.0    36      2               2               4   

   Annual_Income  Purpose  State  Debt_To_Income  Delinquance_2year  
0        28000.0        6     13            12.3                  0

In [32]:
encoded_input=encoded_input.drop("Int_Rate",axis=1)
#y=loan["Int_Rate"].values.reshape(-1, 1)

In [45]:
#linear regression coefficients

coeff = model.coef_
coeff

array([[  4.30515654e-03,   2.29740904e-03,   9.67902047e-01,
         -1.98971459e-04,   5.09432813e-03,  -1.77915048e-03,
          3.26381653e-03,   7.91800812e-04,   6.54369973e-03,
         -6.02030742e-04]])

In [34]:
user_predict = model.predict(encoded_input)
user_predict

array([[-30.44673319]])

In [42]:
Investment = 4000
Term = 36
Grade = 2
Employment_Len = 2
Home_Ownership = 4
Annual_Income=28000.0
Purpose = 6
State = 13
Debt_To_Income = 12.3
Delinquence_2year = 0




pred_out = (4.30515654e-03*Investment)+(2.29740904e-03*Term)+(9.67902047e-01*Grade)+(-1.98971459e-04*Employment_Len)+(5.09432813e-03*Home_Ownership)+(-1.77915048e-03*Annual_Income)+(3.26381653e-03*Purpose)+(7.91800812e-04*State)+(6.54369973e-03*Debt_To_Income)+(-6.02030742e-04*Delinquence_2year)
pred_out

-30.446733274542996

# 

# Why Would You Give That Loan?

In [20]:
why = pd.read_csv("Loan_Data3.csv")
why = why.loc[why["Grade"]=="G"]
why.head()

Int_Rate  Investment  Term Grade Employment_Len Home_Ownership  \
72       30.79     20000.0    60     G      10+ years       MORTGAGE   
128      30.79     30000.0    60     G      10+ years           RENT   
307      30.79     22100.0    60     G      10+ years       MORTGAGE   
852      30.79     13375.0    60     G      10+ years           RENT   
3780     30.79     16000.0    60     G            n/a       MORTGAGE   

      Annual_Income             Purpose State  Debt_To_Income  \
72         254000.0  debt_consolidation    VA           16.86   
128         40000.0               other    NY           30.86   
307        103000.0  debt_consolidation    OH           37.43   
852         72000.0  debt_consolidation    NY           20.74   
3780       103260.0  debt_consolidation    MI           29.91   

      Delinquance_2year  
72                    1  
128                   1  
307                   0  
852                   0  
3780                  0

In [28]:
why =why.sort_values(by=['Annual_Income'])

new_why = why.filter(["Int_rate", "Investment","Annual_Income","Debt_To_Income","Term","Home_Ownership"],axis=1)
new_why.head(25)

Investment  Annual_Income  Debt_To_Income  Term Home_Ownership
263511     35000.0          300.0          999.00    60       MORTGAGE
356186     20000.0         1000.0          277.11    60           RENT
9867       20000.0         1000.0          277.11    60           RENT
217024     10000.0         1200.0          532.00    60           RENT
273202     10000.0         2500.0          240.87    60           RENT
238528     11500.0         3200.0          128.20    60       MORTGAGE
133827     19250.0         5000.0          287.26    36           RENT
297147      1500.0         6000.0           12.00    36           RENT
284966     17100.0         7764.0           79.60    36           RENT
313419     25000.0         9000.0          110.93    60       MORTGAGE
95913      35000.0        10000.0           71.19    36           RENT
442232     35000.0        10000.0           71.19    36           RENT
251206     22000.0        10000.0           52.70    60           RENT
333266     15950.0        10000.0           79.47    60           RENT
231409     15300.0        10092.0          192.98    60       MORTGAGE
346050     22000.0        10250.0          108.55    60           RENT
339482      3300.0        11000.0            9.26    36           RENT
462214     14075.0        12000.0           34.90    60            OWN
312356     13800.0        12000.0          228.48    60       MORTGAGE
234971     28950.0        12000.0           72.20    60           RENT
115895     14075.0        12000.0           34.90    60            OWN
140972      2875.0        12000.0            7.30    36       MORTGAGE
290656      2300.0        12072.0           27.04    36           RENT
335696     23850.0        12129.0          111.09    60            OWN
295799     13000.0        12525.0           95.40    36           RENT